name: Prettier Check

on:
  pull_request:
    branches:
      - main

jobs:
  prettier:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run Prettier Check
        run: |
          if ! npx prettier --check .; then
            echo "Code formatting issues found. Running prettier to show the diff..."
            npx prettier --write .
            exit 1
          fi
